import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="bg-gradient-to-b from-gray-900 to-gray-800">
          <div className="container mx-auto py-16 px-4">
            <h2 className="text-3xl font-bold text-white">Footer Content</h2>
            <p className="mt-4 text-gray-400">
              This is a simple footer section with a gradient background.
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}
